# Generated by Django 2.2 on 2019-05-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=100, verbose_name='Компонент')),
                ('flow_pump', models.FloatField(verbose_name='Расход, кг/с')),
                ('out_pressure', models.FloatField(verbose_name='Давление неа выходе, бар')),
                ('in_pressure', models.FloatField(verbose_name='Давление на входе, бар')),
                ('steam_pressure', models.FloatField(verbose_name='Давление насыщенного пара, бар')),
                ('in_temperature', models.IntegerField(verbose_name='Температура на входе, К')),
                ('density', models.FloatField(verbose_name='Плотность компонента, кг/м^3')),
                ('viscosity', models.FloatField(verbose_name='Вязкость компонента, Па*с')),
            ],
            options={
                'verbose_name': 'Насос',
                'verbose_name_plural': 'Насосы',
                'ordering': ['pk'],
            },
        ),
    ]
